# Generated by Django 4.2.6 on 2023-10-29 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_forms', '0002_alter_articles_options_articles_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='image',
            field=models.ImageField(default='Null', upload_to='images/'),
        ),
    ]
