# Generated by Django 4.2.6 on 2023-10-30 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_forms', '0003_alter_articles_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Название объявления')),
                ('url', models.URLField(verbose_name='Сылка')),
                ('price', models.CharField(max_length=100, verbose_name='Цена автомобиля')),
                ('description', models.TextField(verbose_name='Описание обявления')),
                ('date_car_par', models.CharField(max_length=70, verbose_name='Дата публикации объявления')),
            ],
        ),
        migrations.AlterField(
            model_name='articles',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
